// <auto-generated />
using EduCloud_v42.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduCloud_v42.Migrations
{
    [DbContext(typeof(LearningDbContext))]
    [Migration("20251108141929_file_name_added_to_task_file")]
    partial class file_name_added_to_task_file
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("EduCloud_v42.Models.Course", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("EduCloud_v42.Models.CourseElement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("course");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("ID");

                    b.HasIndex("CourseId");

                    b.ToTable("Course Element", (string)null);
                });

            modelBuilder.Entity("EduCloud_v42.Models.CourseFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Course element")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseElementId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Course element");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.HasKey("ID");

                    b.HasIndex("Course element");

                    b.ToTable("Course Files", null, t =>
                        {
                            t.Property("Course element")
                                .HasColumnName("Course element1");
                        });
                });

            modelBuilder.Entity("EduCloud_v42.Models.TaskFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Task");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("User");

                    b.HasKey("ID");

                    b.HasIndex("UserId", "TaskId");

                    b.ToTable("Taks Files", (string)null);
                });

            modelBuilder.Entity("EduCloud_v42.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EduCloud_v42.Models.UserCourse", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Users to Courses", (string)null);
                });

            modelBuilder.Entity("EduCloud_v42.Models.UserTask", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("User");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Task");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("User to Task", (string)null);
                });

            modelBuilder.Entity("EduCloud_v42.Models.CourseElement", b =>
                {
                    b.HasOne("EduCloud_v42.Models.Course", "Course")
                        .WithMany("CourseElements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EduCloud_v42.Models.CourseFile", b =>
                {
                    b.HasOne("EduCloud_v42.Models.CourseElement", "CourseElement")
                        .WithMany("CourseFiles")
                        .HasForeignKey("Course element")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseElement");
                });

            modelBuilder.Entity("EduCloud_v42.Models.TaskFile", b =>
                {
                    b.HasOne("EduCloud_v42.Models.UserTask", "UserTask")
                        .WithMany("TaskFiles")
                        .HasForeignKey("UserId", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTask");
                });

            modelBuilder.Entity("EduCloud_v42.Models.UserCourse", b =>
                {
                    b.HasOne("EduCloud_v42.Models.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduCloud_v42.Models.User", "User")
                        .WithMany("UserCourses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduCloud_v42.Models.UserTask", b =>
                {
                    b.HasOne("EduCloud_v42.Models.CourseElement", "Task")
                        .WithMany("UserTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduCloud_v42.Models.User", "User")
                        .WithMany("UserTasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduCloud_v42.Models.Course", b =>
                {
                    b.Navigation("CourseElements");

                    b.Navigation("UserCourses");
                });

            modelBuilder.Entity("EduCloud_v42.Models.CourseElement", b =>
                {
                    b.Navigation("CourseFiles");

                    b.Navigation("UserTasks");
                });

            modelBuilder.Entity("EduCloud_v42.Models.User", b =>
                {
                    b.Navigation("UserCourses");

                    b.Navigation("UserTasks");
                });

            modelBuilder.Entity("EduCloud_v42.Models.UserTask", b =>
                {
                    b.Navigation("TaskFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
